### ISSUE TITLE
Unable to install with `brew install nelstrom/homebrew-vim/vim --with-cdo`

### ISSUE THREAD

**Issue by stevenproctor** [nelstrom/homebrew-vim#1]
When I run `brew install nelstrom/homebrew-vim/vim --with-cdo`

This is the error that results.

```
$ brew install nelstrom/homebrew-vim/vim --with-cdo
==> Tapping nelstrom/homebrew-vim
Cloning into '/usr/local/Library/Taps/nelstrom/homebrew-homebrew-vim'...
remote: Repository not found.
fatal: repository 'https://github.com/nelstrom/homebrew-homebrew-vim/' not found
Error: Failure while executing: git clone https://github.com/nelstrom/homebrew-homebrew-vim /usr/local/Library/Taps/nelstrom/homebrew-homebrew-vim --depth=1
```

**Comment by stevenproctor** [comment]
The second version (`brew install nelstrom/vim/vim --with-cdo`) did work though.

Feel free to close this, or leave this open if you want the data on why the first command failed.

If you do try to address the first command, I would be happy to retest it.

**Comment by nelstrom** [comment]
The [How to Create and Maintain a Tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) article says:

>  If it’s on GitHub, they can use zbrew tap user/repo`, where`user`is your GitHub username and`homebrew-repo` your repository.

So in fact the `brew install nelstrom/vim/vim --with-cdo` command is correct.

I got confused because of this line: 

> If it’s on GitHub, users can install any of your formulae with `brew install user/repo/formula`

which suggests that `brew install nelstrom/homebrew-vim/vim --with-cdo` should work. I'll remove that instruction from the README.
